services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/code/
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    links:
      - db
      - redis

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend/:/app/
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: crypto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your-password
    volumes:
      - db_data:/var/lib/postgresql/data/

  mongo:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db/

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
  db_data:
  mongo_data:
